name: Maven Clean + Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Supprimer le cache Maven local
        run: rm -rf ~/.m2/repository

      - name: Nettoyage du projet (clean)
        run: mvn clean

      - name: Lancer Checkstyle
        run: mvn checkstyle:check
